name: pr-is-wip-action
author: Shiipou <shiishii@nocturlab.fr>
description: Ensure your PR is not in WIP state
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'shield'
  color: 'green'
inputs:
  githubBaseUrl:
    description: "Github Enterprise API url (e.g. https://github.example.com/api/v3)"
    required: false
  continueIfNonPR:
    description: "Continue if the current event is not a PR"
    required: false
    default: 'false'
outputs:
  is-wip:
    description: "Is the PR in WIP state"
