name: PR Title Check

on:
  push:
    branches:
      - stable
      - beta
      - latest
      - "*.x"
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened

jobs:
  pr-is-wip:
    runs-on: ubuntu-latest
    steps:
      - id: pr-is-wip
        name: pr-is-wip
        uses: shiipou/pr-is-wip-action@4-v2-updating-status-of-a-pr-from-another-ci-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      is-wip: ${{ steps.pr-is-wip.outputs.is-wip }}
 
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && needs.pr-is-wip.outputs.is-wip == 'false')
    runs-on: ubuntu-latest
    needs: [ pr-is-wip ]
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          echo "Running build"
